// SQL for the jobs hub table and assembling a full job view with children.
const db = require('../db/connection');
const { NotFoundError } = require('../utils/errors');

// Columns a client may set on create/update (job_number & timestamps excluded —
// job_number is generated atomically, exchange_rate_locked is set by services).
const EDITABLE = [
  'job_type', 'direction', 'created_date', 'shipper_id', 'consignee_id',
  'notify_1_id', 'notify_2_id', 'commodity_id', 'pol_id', 'pod_id',
  'bl_number', 'packages', 'gross_weight', 'net_weight', 'marks',
  'fin_number', 'etd', 'eta', 'status', 'notes', 'internal_notes',
];

const LIST_SELECT = `
  SELECT j.id, j.job_number, j.job_type, j.direction, j.created_date, j.status,
         j.etd, j.eta, j.bl_number, j.is_archived,
         s.name AS shipper_name, c.name AS consignee_name,
         co.name AS commodity_name, pol.name AS pol_name, pod.name AS pod_name
  FROM jobs j
  LEFT JOIN clients s     ON j.shipper_id   = s.id
  LEFT JOIN clients c     ON j.consignee_id = c.id
  LEFT JOIN commodities co ON j.commodity_id = co.id
  LEFT JOIN ports pol     ON j.pol_id       = pol.id
  LEFT JOIN ports pod     ON j.pod_id       = pod.id
`;

function list({ search = '', status = '', includeArchived = false, page = 1, limit = 25 } = {}) {
  const clauses = [];
  const params = [];
  if (!includeArchived) clauses.push('j.is_archived = 0');
  if (status) {
    clauses.push('j.status = ?');
    params.push(status);
  }
  if (search) {
    clauses.push('(j.job_number LIKE ? OR j.bl_number LIKE ? OR s.name LIKE ? OR c.name LIKE ?)');
    const like = `%${search}%`;
    params.push(like, like, like, like);
  }
  const where = clauses.length ? `WHERE ${clauses.join(' AND ')}` : '';

  const total = db
    .prepare(`SELECT COUNT(*) AS c FROM jobs j LEFT JOIN clients s ON j.shipper_id = s.id
              LEFT JOIN clients c ON j.consignee_id = c.id ${where}`)
    .get(...params).c;

  const safeLimit = Math.min(Math.max(Number(limit) || 25, 1), 200);
  const safePage = Math.max(Number(page) || 1, 1);
  const offset = (safePage - 1) * safeLimit;

  const rows = db
    .prepare(`${LIST_SELECT} ${where} ORDER BY j.created_date DESC, j.id DESC LIMIT ? OFFSET ?`)
    .all(...params, safeLimit, offset);

  return { rows, total, page: safePage, limit: safeLimit, pages: Math.ceil(total / safeLimit) || 1 };
}

function getById(id) {
  return db.prepare('SELECT * FROM jobs WHERE id = ?').get(id);
}

// Full job with joined display names + all children (containers, rates, taxes,
// documents, bl_data). Used by the job-detail page and PDF generation.
function getFull(id) {
  const job = db
    .prepare(
      `SELECT j.*,
              s.name AS shipper_name, s.address AS shipper_address, s.tax_id AS shipper_tax_id,
              c.name AS consignee_name, c.address AS consignee_address,
              n1.name AS notify_1_name, n1.address AS notify_1_address,
              n2.name AS notify_2_name, n2.address AS notify_2_address,
              co.name AS commodity_name, co.description AS commodity_description, co.hs_code AS commodity_hs_code,
              pol.name AS pol_name, pol.code AS pol_code,
              pod.name AS pod_name, pod.code AS pod_code
       FROM jobs j
       LEFT JOIN clients s      ON j.shipper_id   = s.id
       LEFT JOIN clients c      ON j.consignee_id = c.id
       LEFT JOIN clients n1     ON j.notify_1_id  = n1.id
       LEFT JOIN clients n2     ON j.notify_2_id  = n2.id
       LEFT JOIN commodities co ON j.commodity_id = co.id
       LEFT JOIN ports pol      ON j.pol_id       = pol.id
       LEFT JOIN ports pod      ON j.pod_id       = pod.id
       WHERE j.id = ?`
    )
    .get(id);
  if (!job) return null;

  job.containers = db
    .prepare(
      `SELECT ct2.*, t.code AS container_type_code, t.description AS container_type_description
       FROM containers ct2 LEFT JOIN container_types t ON ct2.container_type_id = t.id
       WHERE ct2.job_id = ? ORDER BY ct2.id`
    )
    .all(id);
  job.rates = db
    .prepare(
      `SELECT r.*, v.name AS vendor_name FROM rates r
       LEFT JOIN clients v ON r.vendor_id = v.id WHERE r.job_id = ? ORDER BY r.rate_type, r.id`
    )
    .all(id);
  job.taxes = db.prepare('SELECT * FROM taxes WHERE job_id = ? ORDER BY tax_type').all(id);
  job.documents = db
    .prepare('SELECT * FROM documents WHERE job_id = ? ORDER BY generated_date DESC, id DESC')
    .all(id);
  job.bl_data = db.prepare('SELECT * FROM bl_data WHERE job_id = ?').get(id) || null;
  return job;
}

// Create a job (+ optional containers) atomically. job_number is passed in
// already-generated by jobNumberService.
function create(jobNumber, data, containers = []) {
  const tx = db.transaction(() => {
    // Only write columns the caller actually provided so NOT NULL columns with
    // schema defaults (job_type, direction, status) fall back correctly.
    const provided = EDITABLE.filter((c) => data[c] !== undefined && data[c] !== null && data[c] !== '');
    const cols = ['job_number', ...provided];
    const values = [jobNumber, ...provided.map((c) => data[c])];
    const placeholders = cols.map(() => '?').join(', ');
    const info = db.prepare(`INSERT INTO jobs (${cols.join(', ')}) VALUES (${placeholders})`).run(...values);
    const jobId = info.lastInsertRowid;

    const insC = db.prepare(
      `INSERT INTO containers (job_id, container_number, container_type_id, seal_number,
        vessel, voyage, status, pickup_location, pickup_date, delivery_date)
       VALUES (?,?,?,?,?,?,?,?,?,?)`
    );
    for (const c of containers) {
      insC.run(
        jobId, c.container_number || null, c.container_type_id || null, c.seal_number || null,
        c.vessel || null, c.voyage || null, c.status || 'EMPTY', c.pickup_location || null,
        c.pickup_date || null, c.delivery_date || null
      );
    }
    return jobId;
  });
  return tx();
}

const NOT_NULL_COLS = new Set(['job_type', 'direction', 'status']);

function update(id, data) {
  if (!getById(id)) throw new NotFoundError(`Job #${id} not found.`);
  // Only update provided keys. Never null a NOT NULL column via an empty value.
  const cols = EDITABLE.filter((c) => {
    if (data[c] === undefined) return false;
    if (NOT_NULL_COLS.has(c) && (data[c] === null || data[c] === '')) return false;
    return true;
  });
  if (cols.length) {
    const set = cols.map((c) => `${c} = ?`).join(', ');
    const values = cols.map((c) => (data[c] === '' ? null : data[c]));
    db.prepare(`UPDATE jobs SET ${set} WHERE id = ?`).run(...values, id);
  }
  return getById(id);
}

function setArchived(id, archived) {
  if (!getById(id)) throw new NotFoundError(`Job #${id} not found.`);
  db.prepare('UPDATE jobs SET is_archived = ? WHERE id = ?').run(archived ? 1 : 0, id);
  return getById(id);
}

function lockExchangeRate(id, rate) {
  db.prepare('UPDATE jobs SET exchange_rate_locked = ? WHERE id = ?').run(rate, id);
}

// A job is "financially active" once any rate is PAID or any document exists —
// such jobs must be archived, never hard-deleted (Improvement #6 / Rule #5).
function isFinanciallyActive(id) {
  const paid = db.prepare("SELECT 1 FROM rates WHERE job_id = ? AND paid_status = 'PAID' LIMIT 1").get(id);
  const doc = db.prepare('SELECT 1 FROM documents WHERE job_id = ? LIMIT 1').get(id);
  return Boolean(paid || doc);
}

function remove(id) {
  db.prepare('DELETE FROM jobs WHERE id = ?').run(id);
}

// Dashboard quick-stats.
function stats() {
  const byStatus = db
    .prepare('SELECT status, COUNT(*) AS c FROM jobs WHERE is_archived = 0 GROUP BY status')
    .all();
  const map = { BOOKED: 0, SAILED: 0, DELIVERED: 0, CLOSED: 0, CANCELLED: 0 };
  for (const r of byStatus) map[r.status] = r.c;
  const total = db.prepare('SELECT COUNT(*) AS c FROM jobs WHERE is_archived = 0').get().c;
  return { total, ...map };
}

module.exports = {
  list, getById, getFull, create, update, setArchived,
  lockExchangeRate, isFinanciallyActive, remove, stats, EDITABLE,
};
